---
- name: Verify
  hosts: all
  become: true

  tasks:
    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Check tigervnc-server package is installed  # noqa command-instead-of-module
      ansible.builtin.command: rpm -q tigervnc-server
      register: tigervnc_pkg
      changed_when: false

    - name: Assert tigervnc-server is installed
      ansible.builtin.assert:
        that:
          - tigervnc_pkg.rc == 0
        fail_msg: "tigervnc-server is NOT installed"
        success_msg: "tigervnc-server is installed"

    - name: Check vncpasswd command exists
      ansible.builtin.command: bash -lc "command -v vncpasswd"
      register: vncpasswd_cmd
      changed_when: false

    - name: Assert vncpasswd exists
      ansible.builtin.assert:
        that:
          - vncpasswd_cmd.rc == 0
        fail_msg: "vncpasswd command is NOT available"
        success_msg: "vncpasswd command is available"
